vim.keymap.set("n", "<leader>nb", ":bnext<CR>")
vim.keymap.set("n", "<leader>pb", ":bprev<CR>")
vim.keymap.set("n", "<leader>d", ":bd<CR>")
vim.keymap.set("n", "<leader>ns", ":nohlsearch<CR>")
vim.keymap.set("n", "<C-n>", ":Neotree filesystem reveal left<CR>")
vim.keymap.set("i", "<C-h>", "<C-Left>")
vim.keymap.set("i", "<C-j>", "<Down>")
vim.keymap.set("i", "<C-k>", "<Up>")
vim.keymap.set("i", "<C-l>", "<C-Right>")
vim.keymap.set("i", "<M-h>", "<Left>")
vim.keymap.set("i", "<M-l>", "<Right>")
vim.keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, {})
vim.keymap.set({ "n", "v" }, "<leader>i", vim.lsp.buf.format, {})
vim.keymap.set("n", "<A-j>", ":m .+1<CR>==")
vim.keymap.set("n", "<A-k>", ":m .-2<CR>==")
vim.keymap.set("v", "<A-j>", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "<A-k>", ":m '<-2<CR>gv=gv")

local function termSplit()
  vim.cmd("split")
  vim.cmd("wincmd j")
  vim.cmd("term")
end

vim.keymap.set("n", "<C-\\>", ":vsplit<CR>")
vim.keymap.set("n", "<C-S-\\>", ":split<CR>")
vim.keymap.set("n", "<leader>t", termSplit)
